name: Multi-Platform Matrix Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18, 20]
        include:
          - os: ubuntu-latest
            artifact-name: linux
          - os: macos-latest
            artifact-name: macos
          - os: windows-latest
            artifact-name: windows
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: matrix-594f6f9
        run: |
          echo "Building for ${{ matrix.os }} with Node ${{ matrix.node-version }}"
          echo "Artifact will be: build-594f6f9-${{ matrix.artifact-name }}-node${{ matrix.node-version }}"
      
      - name: Generate build artifact
        run: |
          echo "Build Information" > build-output.txt
          echo "==================" >> build-output.txt
          echo "OS: ${{ matrix.os }}" >> build-output.txt
          echo "Node Version: ${{ matrix.node-version }}" >> build-output.txt
          echo "Timestamp: $(date)" >> build-output.txt
          echo "Runner: ${{ runner.os }}" >> build-output.txt
          echo "" >> build-output.txt
          echo "Build completed successfully!" >> build-output.txt
        shell: bash
      
      - name: Display artifact content
        run: cat build-output.txt
        shell: bash
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-594f6f9-${{ matrix.artifact-name }}-node${{ matrix.node-version }}
          path: build-output.txt
          retention-days: 30
